//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Archivos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Archivos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Recursos.Archivos", typeof(Archivos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto Simple	45.
        /// </summary>
        internal static string Proyecto1 {
            get {
                return ResourceManager.GetString("Proyecto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	nombre : &quot;Proyecto con dos tareas&quot;,
        ///	tareas : [{
        ///			nombre : &quot;Tarea 1&quot;,
        ///			porcentaje : 10
        ///		}, {
        ///			nombre : &quot;Tarea 2&quot;,
        ///			porcentaje : 36
        ///		}, {
        ///			nombre : &quot;Tarea con subtareas&quot;,
        ///			tareas : [{
        ///					nombre : &quot;Subtarea 1&quot;,
        ///					porcentaje : 100
        ///				}, {
        ///					nombre : &quot;Subtarea 2&quot;,
        ///					porcentaje : 76
        ///				}
        ///			]
        ///		}
        ///	]
        ///}.
        /// </summary>
        internal static string Proyecto2 {
            get {
                return ResourceManager.GetString("Proyecto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto con dos tareas: 44
        ///	Tarea 1: 10
        ///	Tarea 2: 36
        ///	Tarea con subtareas: 88
        ///		Subtarea 1: 100
        ///		Subtarea 1: 76.
        /// </summary>
        internal static string ResumenEsperadoProyecto2 {
            get {
                return ResourceManager.GetString("ResumenEsperadoProyecto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1	100000
        ///P2	80000
        ///P3	30000
        ///P4	20000.
        /// </summary>
        internal static string VotacionEsquema1 {
            get {
                return ResourceManager.GetString("VotacionEsquema1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1	340000
        ///P2	280000
        ///P3	160000
        ///P4	60000
        ///P5	15000.
        /// </summary>
        internal static string VotacionEsquema2 {
            get {
                return ResourceManager.GetString("VotacionEsquema2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1	391000
        ///P2	311000
        ///P3	184000
        ///P4	73000
        ///P5	27000
        ///P6	12000
        ///P7	2000.
        /// </summary>
        internal static string VotacionEsquema3 {
            get {
                return ResourceManager.GetString("VotacionEsquema3", resourceCulture);
            }
        }
    }
}
