// <auto-generated />
namespace Politecnico.Patrones.ProyectoFinal.Lib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CambioTabla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambioTabla));
        
        string IMigrationMetadata.Id
        {
            get { return "201505192010321_CambioTabla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
