//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politecnico.Patrones.ProyectoFinal.Lib.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Consultas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Consultas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Politecnico.Patrones.ProyectoFinal.Lib.Recursos.Consultas", typeof(Consultas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.Id, a.FchCreacion, a.Nombre, a.AñoLanzamiento
        ///	, COUNT(DISTINCT vu.Id) TotalVotos
        ///FROM Album a
        ///INNER JOIN VotableUsuario vu ON vu.VotableId = a.VotableId
        ///WHERE vu.FchCreacion BETWEEN @FchInicio AND @FchFin
        ///GROUP BY a.Id, a.FchCreacion, a.Nombre, a.AñoLanzamiento.
        /// </summary>
        public static string rpt_albumes {
            get {
                return ResourceManager.GetString("rpt_albumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.Id, c.FchCreacion, c.Nombre
        ///	, ISNULL(a.Nombre, &apos;No disponible&apos;) &apos;Album&apos;
        ///	, COUNT(DISTINCT vu.Id) TotalVotos
        ///FROM Cancion c
        ///LEFT JOIN Album a ON c.AlbumId = a.Id
        ///INNER JOIN VotableUsuario vu ON vu.VotableId = c.VotableId
        ///WHERE vu.FchCreacion BETWEEN @FchInicio AND @FchFin
        ///GROUP BY c.Id, c.FchCreacion, c.AlbumId, c.Nombre, a.Nombre.
        /// </summary>
        public static string rpt_canciones {
            get {
                return ResourceManager.GetString("rpt_canciones", resourceCulture);
            }
        }
    }
}
