//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politecnico.Patrones.Decorador01.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Archivos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Archivos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Politecnico.Patrones.Decorador01.Recursos.Archivos", typeof(Archivos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À	&amp;Agrave;
        ///È	&amp;Egrave;
        ///Ì	&amp;Igrave;
        ///Ò	&amp;Ograve;
        ///Ù	&amp;Ugrave;
        ///à	&amp;agrave;
        ///è	&amp;egrave;
        ///ì	&amp;igrave;
        ///ò	&amp;ograve;
        ///ù	&amp;ugrave;
        ///Á	&amp;Aacute;
        ///Á	&amp;Aacute;
        ///É	&amp;Eacute;
        ///Í	&amp;Iacute;
        ///Ó	&amp;Oacute;
        ///Ú	&amp;Uacute;
        ///Ý	&amp;Yacute;
        ///á	&amp;aacute;
        ///é	&amp;eacute;
        ///í	&amp;iacute;
        ///ó	&amp;oacute;
        ///ú	&amp;uacute;
        ///ý	&amp;yacute;
        ///Â	&amp;Acirc;
        ///Ê	&amp;Ecirc;
        ///Î	&amp;Icirc;
        ///Ô	&amp;Ocirc;
        ///Û	&amp;Ucirc;
        ///â	&amp;acirc;
        ///ê	&amp;ecirc;
        ///î	&amp;icirc;
        ///ô	&amp;ocirc;
        ///û	&amp;ucirc;
        ///Ã	&amp;Atilde;
        ///Ñ	&amp;Ntilde;
        ///Õ	&amp;Otilde;
        ///ã	&amp;atilde;
        ///ñ	&amp;ntilde;
        ///õ	&amp;otilde;
        ///Ä	&amp;Auml;
        ///Ë	&amp;Euml;
        ///Ï	&amp;Iuml;
        ///Ö	&amp;Ouml;
        ///Ü	&amp;Uuml;
        ///Ÿ	&amp;Y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReemplazosAcentos {
            get {
                return ResourceManager.GetString("ReemplazosAcentos", resourceCulture);
            }
        }
    }
}
